Repository wp-cli/scaffold-command, pull requests merged in 2018-10, with the labels that each got.

#176 Fix syntax error in block-php.mustache
  templates/block-php.mustache
Labels: bug, command:scaffold-block

#177 Allow for `installation` as well as `install`
  features/scaffold.feature
Labels: scope:testing

#178 Ignore 'node_modules' in PHPCS XML file
  templates/.phpcs.xml.dist
Labels: command:scaffold-plugin-tests

#182 Work around Travis CI issue with _s download certificate
  features/scaffold.feature
  src/Scaffold_Command.php
Labels: command:scaffold-_s, scope:testing

#179 Add support for Probot `move` command
  .github/move.yml
Labels: scope:distribution

#180 Fix typo in Travis config
  .travis.yml
Labels: scope:testing
