Repository wp-cli/scaffold-command, pull requests merged in 2020-06, with the labels that each got.

#264 Bump PHPCS compatibility tests to new PHP 5.6+ minimum
  phpcs.xml.dist
Labels: scope:testing

#265 Updated minimum required PHP version to 5.6
  composer.json
Labels: scope:distribution

#270 GitHub workflow files should be ignored on build
  templates/plugin-distignore.mustache
Labels: command:scaffold-plugin
