Repository wp-cli/scaffold-command, pull requests merged in 2020-04, with the labels that each got.

#255 Use longer option names in `install_db()` to avoid stalling CIs
  templates/install-wp-tests.sh
Labels: command:scaffold-plugin-tests

#254 Fix Travis CI `sudo` warning
  .travis.yml
Labels: scope:distribution

#259 Enforce PHP 7.4 compatibility in Travis CI
  .travis.yml
Labels: scope:testing

#260 Bump Travis CI OS from `trusty` to `xenial`
  .travis.yml
  composer.json
  features/scaffold.feature
Labels: scope:testing
