Repository wp-cli/scaffold-command, pull requests merged in 2024-04, with the labels that each got.

#332 Update trunk test to require PHP 7.2
  features/install-wp-tests.feature
Labels: scope:testing

#331 Add GitHub as valid CI for plugin and theme scaffold
  src/Scaffold_Command.php
  templates/plugin-github.mustache
Labels: command:scaffold-plugin-tests

#336 Update theme tests to remove P2 and use TwentyTwelve
  features/scaffold-block.feature
  features/scaffold-theme-tests.feature
Labels: scope:testing

#329 Update scaffold command examples
  README.md
  src/Scaffold_Command.php
Labels: scope:documentation

#335 Correct plugin main file in bootstrap in scaffolded test
  features/scaffold-plugin-tests.feature
  src/Scaffold_Command.php
  templates/plugin-bootstrap.mustache
Labels: command:scaffold-plugin-tests
